config/routes.rb
Rails.application.routes.draw do
  
  resources :projects, only: [:index, :show, :new, :create] do
    resources :funding_levels, only: [:new, :create] 
    resources :pledges, only: [:new, :create]
  end

  root 'projects#index'

end

app/models/funding_level.rb
class FundingLevel < ActiveRecord::Base
  has_many :pledges, dependent: :nullify
  belongs_to :project

  validates :project_id, :reward_name, :amount, presence: true
  validates :reward_name, length: { minimum: 3 }
  validates :amount, numericality: { only_integer: true, :greater_than => 0 } 
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :funding_level
  #belongs_to :project

  validates :funding_level_id, :name, :email, :amount, presence: true
  validates :amount, numericality: { only_integer: true, :greater_than => 0 }

  def fetch_funding_level(project)
    project.all_funding_levels.each do |level|
      if level.amount <= self.amount
        self.funding_level_id = level.id
      end
    end
  end

  def reward_name
    funding_level.reward_name
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :funding_levels, dependent: :nullify
  has_many :pledges, :through => :funding_levels 

  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true

  def all_funding_levels
    self.funding_levels.order(amount: :asc)
  end

  def all_pledges
    self.pledges.order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/funding_levels_controller.rb
class FundingLevelsController < ApplicationController
  before_action :lookup_project

  def new
    @funding_level = @project.funding_levels.new
  end

  def create
    @funding_level = @project.funding_levels.new(funding_level_params)

    if @funding_level.save
      redirect_to project_path(@project), notice: 'Funding level added!!'
    else
      render 'new'
    end
  end

  private

  def lookup_project
    @project = Project.find(params[:project_id])
  end

  def funding_level_params
    params.require(:funding_level).permit(:reward_name, :amount)
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_action :lookup_project

  def new
    @pledge = @project.pledges.new
  end

  def create
    @pledge = @project.pledges.new(pledge_params)
    @pledge.fetch_funding_level(@project)

    if @pledge.save
      redirect_to project_path(@project), notice: 'Pledge added!!'
    else
      render 'new'
    end
  end

  private

  def lookup_project
    @project = Project.find(params[:project_id])
  end

  def pledge_params
    params.require(:pledge).permit(:name, :email, :amount)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order(created_at: :desc)
  end

  def show
    @project = Project.find(params[:id])
    @pledge = Pledge.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path, notice: 'Project created!!'
    else
      render :new
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funding_levels_helper.rb
module FundingLevelsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/funding_levels/_form.html.erb
<div class='errors'>
  <ul>
    <% @funding_level.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<%= form_for([@project, @funding_level]) do |f| %>
  <%= f.label :project_id, 'Project:' %>
  <%= @project.name %>
  <br><br>
  <%= f.label :reward_name, 'Reward:' %>
  <%= f.text_field :reward_name, required: true %>
  <br>
  <%= f.label :amount, 'Amount:' %>
  <%= f.number_field :amount, required: true %>
  <br>
  <%= f.submit 'Save', class: "button-primary" %>
<% end %>

app/views/funding_levels/new.html.erb
<h2>New Funding Level</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'stylesheets/normalize', :media => 'screen' %>
  <%= stylesheet_link_tag 'stylesheets/skeleton', :media => 'screen' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <h1>My Awesome Crowdfunder App</h1>
</header>

<% flash.each do |key, msg| %>
  <p class="flash-<%= key %>"><%= msg %></p>
<% end %>

<%= yield %>

<footer>
  <small>Created by Maria Aranibar - 2015</small>
</footer>

</body>
</html>

app/views/pledges/_form.html.erb
<div class='errors'>
  <ul>
    <% @pledge.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<%= form_for([@project, @pledge]) do |f| %>
  <%= f.label :project_id, 'Project:' %>
  <%= @project.name %>
  <br><br>
  <%= f.label :name, 'Name:' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email, 'Email:' %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :amount, 'Amount:' %>
  <%= f.number_field :amount %>
  <br>
  <%= f.submit 'Save', class: "button-primary" %>
<% end %>

app/views/pledges/new.html.erb
<h2>New Pledge</h2>

<%= render 'form' %>

app/views/projects/_form.html.erb
<div class='errors'>
  <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<%= form_for @project do |f| %>
  <%= f.label :name, 'What\'s the name of your Project?' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :description, 'Tell us about it:' %>
  <%= f.text_area :description %>
  <br>
  <%= f.submit 'Save', class: "button-primary" %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<h2>Projects</h2>

<br>
<p><%= link_to 'New Project', new_project_path %></p>
<br>

<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project_path(project) %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render 'form' %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>

<div class='description'>
  <%= @project.description %>
</div>
<br>
<h3>Funding Levels</h3>
<ul>
  <% @project.all_funding_levels.each do |f_level| %>
    <li>
      <%= f_level.reward_name + ' - $' + f_level.amount.to_s %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add new funding level', new_project_funding_level_path(@project) %>
<br><br>
<h3>Pledges</h3>
<ul>
  <% @project.all_pledges.each do |pledge| %>
    <li>
      <%= pledge.name + ' (' + pledge.reward_name + ')' %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add new pledge', new_project_pledge_path(@project) %> 
<br><br>
<h3>Make a pledge</h3>
<%= render 'pledges/form' %>